BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "DEMONS" (
	"DEMON_ID"	INTEGER NOT NULL UNIQUE,
	"NAME"	TEXT UNIQUE,
	"ELEMENT"	TEXT,
	"ARCANA"	TEXT,
	"RARITY"	INTEGER,
	"IMG"	TEXT UNIQUE,
	"MIN_RANGE"	INTEGER,
	"MAX_RANGE"	INTEGER,
	"ELEMENT_WK"	TEXT,
	PRIMARY KEY("DEMON_ID")
);
CREATE TABLE IF NOT EXISTS "USERS" (
	"USER_ID"	TEXT NOT NULL UNIQUE,
	"LEVEL"	INTEGER,
	PRIMARY KEY("USER_ID")
);
CREATE TABLE IF NOT EXISTS "PERSONA" (
	"USER_ID"	TEXT NOT NULL,
	"DEMON_ID"	INTEGER NOT NULL,
	"QTY"	INTEGER,
	PRIMARY KEY("USER_ID","DEMON_ID"),
	FOREIGN KEY("DEMON_ID") REFERENCES "DEMONS"("DEMON_ID") ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY("USER_ID") REFERENCES "USERS"("USER_ID") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "DEMONS" VALUES (1,'Abaddon','curse','Devil',3,'nC3KQbz.png',35,70,'bless');
INSERT INTO "DEMONS" VALUES (2,'Alice','curse','Death',3,'3hhm2Zb.png',40,56,'bless');
INSERT INTO "DEMONS" VALUES (3,'Alilat','ice','Empress',4,'FxCVWBA.png',57,84,'electricity');
INSERT INTO "DEMONS" VALUES (4,'Alp','wind','Lovers',1,'zU2hne4.png',3,6,'ice');
INSERT INTO "DEMONS" VALUES (5,'Ananta','ice','Hierophant',2,'Jg5jo9J.png',24,41,'electricity');
INSERT INTO "DEMONS" VALUES (6,'Angel','bless','Justice',1,'Hdj1RNh.png',1,4,'curse');
INSERT INTO "DEMONS" VALUES (7,'Anubis','bless','Judgement',3,'SlEzC3w.png',45,58,NULL);
INSERT INTO "DEMONS" VALUES (8,'Apsaras','ice','Priestess',1,'1KDiic8.png',2,3,'physical');
INSERT INTO "DEMONS" VALUES (9,'Ara Mitama','physical','Chariot',1,'egtPw2e.png',4,6,'wind');
INSERT INTO "DEMONS" VALUES (10,'Arahabaki','fire','Hermit',3,'uyapxm2.png',32,54,'physical');
INSERT INTO "DEMONS" VALUES (11,'Archangel','bless','Justice',1,'IuGmSNX.png',5,10,'curse');
INSERT INTO "DEMONS" VALUES (12,'Ares','physical','Chariot',1,'kdKpemu.png',10,19,'wind');
INSERT INTO "DEMONS" VALUES (13,'Asura','fire','Sun',4,'Wl7D6zA.png',60,85,'curse');
INSERT INTO "DEMONS" VALUES (14,'Atavanka','bless','Chariot',4,'5T5aIQe.png',65,80,'curse');
INSERT INTO "DEMONS" VALUES (15,'Atropos','wind','Fortune',3,'i6OmFaL.png',36,54,'electricity');
INSERT INTO "DEMONS" VALUES (16,'Attis','fire','Hanged Man',3,'ZgnxIHJ.png',39,58,'curse');
INSERT INTO "DEMONS" VALUES (17,'Baal Zebul','ice','Moon',3,'M49HrJW.png',43,71,'fire');
INSERT INTO "DEMONS" VALUES (18,'Barong','physical','Emperor',3,'JP5JPFg.png',32,52,'wind');
INSERT INTO "DEMONS" VALUES (19,'Beelzebub','fire','Devil',4,'Ps8NyBx.png',67,81,'bless');
INSERT INTO "DEMONS" VALUES (20,'Berith','fire','Hierophant',1,'aYzvjye.png',4,13,'electricity');
INSERT INTO "DEMONS" VALUES (21,'Bishamonten','fire','Tower',3,'jWP4ZLr.png',50,60,'ice');
INSERT INTO "DEMONS" VALUES (22,'Black Frost','curse','Fool',2,'0YdXqah.png',15,34,'bless');
INSERT INTO "DEMONS" VALUES (23,'Byakko','ice','Temperance',3,'1tpgzLh.png',40,56,'fire');
INSERT INTO "DEMONS" VALUES (24,'Chernobog','physical','Moon',3,'xah3zUp.png',35,58,'wind');
INSERT INTO "DEMONS" VALUES (25,'Chi You','physical','Tower',4,'EY71ovy.png',55,86,'electricity');
INSERT INTO "DEMONS" VALUES (26,'Chimera','physical','Chariot',1,'ZKAdM7q.png',2,9,'ice');
INSERT INTO "DEMONS" VALUES (27,'Clotho','wind','Fortune',2,'Y8rCWAD.png',12,33,'fire');
INSERT INTO "DEMONS" VALUES (28,'Cu Chulainn','physical','Tower',2,'mBtUW1o.png',18,40,'curse');
INSERT INTO "DEMONS" VALUES (29,'Cybele','bless','Lovers',3,'kseBNBf.png',41,68,'electricity');
INSERT INTO "DEMONS" VALUES (30,'Daisoujou','bless','Hierophant',3,'p2u3bjX.png',45,53,'curse');
INSERT INTO "DEMONS" VALUES (31,'Decarabia','fire','Fool',2,'PNITCgt.png',17,44,'physical');
INSERT INTO "DEMONS" VALUES (32,'Dionysus','electricity','Moon',2,'EcC7uY3.png',20,48,'wind');
INSERT INTO "DEMONS" VALUES (33,'Dominion','bless','Justice',2,'d3SYIvr.png',22,42,'curse');
INSERT INTO "DEMONS" VALUES (34,'Eligor','physical','Tower',2,'oEM9Jss.png',15,31,'bless');
INSERT INTO "DEMONS" VALUES (35,'Empusa','wind','Fortune',1,'HPVpjKP.png',14,23,'fire');
INSERT INTO "DEMONS" VALUES (36,'Flauros','fire','Hierophant',1,'vc8ZjDb.png',10,23,'wind');
INSERT INTO "DEMONS" VALUES (37,'Forneus','ice','Emperor',1,'7IhFNKN.png',3,7,'fire');
INSERT INTO "DEMONS" VALUES (38,'Fortuna','wind','Fortune',1,'ZV6f7AK.png',6,17,'fire');
INSERT INTO "DEMONS" VALUES (39,'Gabriel','ice','Empress',3,'1fLX5Ho.png',36,62,'curse');
INSERT INTO "DEMONS" VALUES (40,'Ganesha','physical','Star',3,'AB0LFVB.png',42,58,'curse');
INSERT INTO "DEMONS" VALUES (41,'Ganga','ice','Priestess',1,'H7wDnea.png',11,26,'fire');
INSERT INTO "DEMONS" VALUES (42,'Garuda','wind','Star',3,'QYWVFEP.png',45,65,'electricity');
INSERT INTO "DEMONS" VALUES (43,'Genbu','ice','Temperance',1,'By6Fb4Q.png',7,29,'electricity');
INSERT INTO "DEMONS" VALUES (44,'Ghoul','curse','Death',1,'nvM5Xw2.png',1,18,'physical');
INSERT INTO "DEMONS" VALUES (45,'Girimehkala','physical','Moon',2,'gquqWcv.png',25,42,'wind');
INSERT INTO "DEMONS" VALUES (46,'Gurr','physical','Moon',2,'lbKB1HP.png',16,42,'wind');
INSERT INTO "DEMONS" VALUES (47,'Hanuman','physical','Strength',2,'IGsVisi.png',20,37,'wind');
INSERT INTO "DEMONS" VALUES (48,'Hariti','ice','Empress',3,'R3cBwKG.png',41,57,'electricity');
INSERT INTO "DEMONS" VALUES (49,'Hecatoncheir','physical','Hanged Man',3,'ykYkgQX.png',34,54,'bless');
INSERT INTO "DEMONS" VALUES (50,'Helel','fire','Star',4,'KtajYn0.png',60,88,'ice');
INSERT INTO "DEMONS" VALUES (51,'Hell Biker','fire','Hanged Man',3,'CzxdI60.png',39,60,'electricity');
INSERT INTO "DEMONS" VALUES (52,'High Pixie','ice','Priestess',1,'GAr7JUe.png',8,21,'wind');
INSERT INTO "DEMONS" VALUES (53,'Hokuto Seikun','electricity','Hierophant',2,'Rto9le8.png',19,31,'wind');
INSERT INTO "DEMONS" VALUES (54,'Horus','bless','Sun',3,'URSZ8xY.png',45,63,'curse');
INSERT INTO "DEMONS" VALUES (55,'Hua Po','fire','Magician',1,'CzuoduN.png',9,20,'ice');
INSERT INTO "DEMONS" VALUES (56,'Incubus','fire','Devil',2,'k4d2YKd.png',18,34,'ice');
INSERT INTO "DEMONS" VALUES (57,'Inugami','physical','Hanged Man',1,'IQae9x2.png',7,10,'wind');
INSERT INTO "DEMONS" VALUES (58,'Jack Frost','ice','Magician',1,'VeZbBAc.png',4,8,'fire');
INSERT INTO "DEMONS" VALUES (59,'Jatayu','wind','Sun',3,'AnUQrAZ.png',38,55,'electricity');
INSERT INTO "DEMONS" VALUES (60,'Jikokuten','physical','Strength',1,'Ic707oE.png',18,29,'curse');
INSERT INTO "DEMONS" VALUES (61,'Kaiwan','physical','Star',2,'8VF7pD6.png',20,49,'electricity');
INSERT INTO "DEMONS" VALUES (62,'Kali','physical','Strength',2,'pnEtg5K.png',18,49,'wind');
INSERT INTO "DEMONS" VALUES (63,'Kartikeya','physical','Star',3,'ZNq4wlI.png',46,70,'fire');
INSERT INTO "DEMONS" VALUES (64,'Kikuri-Hime','bless','Priestess',3,'p6wFH6b.png',45,70,'curse');
INSERT INTO "DEMONS" VALUES (65,'King Frost','ice','Emperor',1,'rBHyZIZ.png',15,30,'fire');
INSERT INTO "DEMONS" VALUES (66,'Kingu','bless','Emperor',2,'4YiEh9j.png',22,46,'fire');
INSERT INTO "DEMONS" VALUES (67,'Kohryu','electricity','Hierophant',3,'a0XBaN7.png',50,61,NULL);
INSERT INTO "DEMONS" VALUES (68,'Koumokuten','physical','Chariot',2,'ASqiGTl.png',25,43,'fire');
INSERT INTO "DEMONS" VALUES (69,'Kumbhanda','fire','Hermit',3,'kaqYg1q.png',37,56,'wind');
INSERT INTO "DEMONS" VALUES (70,'Kurama Tengu','wind','Hermit',2,'gwm5scs.png',20,41,'electricity');
INSERT INTO "DEMONS" VALUES (71,'Kusi Mitama','wind','Fortune',1,'CVAu1e3.png',11,23,'curse');
INSERT INTO "DEMONS" VALUES (72,'Lachesis','wind','Fortune',2,'LCIY5FQ.png',15,45,'electricity');
INSERT INTO "DEMONS" VALUES (73,'Lakshmi','ice','Empress',2,'WNeyZFJ.png',21,47,'fire');
INSERT INTO "DEMONS" VALUES (74,'Lamia','curse','Hermit',1,'2puYR0Y.png',13,25,'physical');
INSERT INTO "DEMONS" VALUES (75,'Leanan Sidhe','bless','Empress',2,'El6jY3k.png',17,33,'electricity');
INSERT INTO "DEMONS" VALUES (76,'Legion','curse','Fool',1,'omXnYZU.png',4,12,'bless');
INSERT INTO "DEMONS" VALUES (77,'Lilim','curse','Devil',1,'HHOjsvG.png',5,8,'bless');
INSERT INTO "DEMONS" VALUES (78,'Lilith','curse','Devil',3,'6Q2Jchq.png',43,61,'bless');
INSERT INTO "DEMONS" VALUES (79,'Loa','curse','Death',1,'hn5Hht7.png',3,19,'bless');
INSERT INTO "DEMONS" VALUES (80,'Loki','ice','Fool',3,'7sbasCo.png',31,55,'fire');
INSERT INTO "DEMONS" VALUES (81,'Lucifer','curse','Judgement',4,'qP3hiE9.png',72,89,'bless');
INSERT INTO "DEMONS" VALUES (82,'Mara','physical','Tower',3,'bWzWqYB.png',40,77,'ice');
INSERT INTO "DEMONS" VALUES (83,'Masakado','curse','Tower',3,'ArP1nBB.png',46,73,'electricity');
INSERT INTO "DEMONS" VALUES (84,'Melichizedek','bless','Justice',3,'guKG5D4.png',33,59,'curse');
INSERT INTO "DEMONS" VALUES (85,'Messiah','bless','Judgement',0,'G3514iq.png',82,90,'curse');
INSERT INTO "DEMONS" VALUES (86,'Metatron','bless','Sun',3,'6ssH7ay.png',66,75,'curse');
INSERT INTO "DEMONS" VALUES (87,'Michael','bless','Judgement',3,'ULWtr6Q.png',38,72,'curse');
INSERT INTO "DEMONS" VALUES (88,'Mithra','ice','Temperance',1,'xoHNVzs.png',9,22,'electricity');
INSERT INTO "DEMONS" VALUES (89,'Mot','curse','Death',2,'iu6diZd.png',24,45,'bless');
INSERT INTO "DEMONS" VALUES (90,'Mother Harlot','electricity','Empress',3,'WpWrCwo.png',39,69,'fire');
INSERT INTO "DEMONS" VALUES (91,'Mothman','electricity','Hermit',2,'072FUPI.png',16,32,'physical');
INSERT INTO "DEMONS" VALUES (92,'Naga','physical','Hermit',1,'l7CEf27.png',6,17,'bless');
INSERT INTO "DEMONS" VALUES (93,'Nandi','wind','Star',2,'DdAJTnf.png',25,39,'fire');
INSERT INTO "DEMONS" VALUES (94,'Narasimha','physical','Strength',2,'RH01YSg.png',19,46,'wind');
INSERT INTO "DEMONS" VALUES (95,'Narcissus','curse','Lovers',1,'e43xLVM.png',11,20,'physical');
INSERT INTO "DEMONS" VALUES (96,'Nata Taishi','physical','Chariot',2,'Xx8DUle.png',21,37,'ice');
INSERT INTO "DEMONS" VALUES (97,'Nebiros','fire','Hermit',2,'sHmXHoD.png',28,50,'bless');
INSERT INTO "DEMONS" VALUES (98,'Nekomata','fire','Magician',1,'kqwRjEL.png',1,5,'electricity');
INSERT INTO "DEMONS" VALUES (99,'Nidhoggr','curse','Hermit',3,'Bm1AQ5E.png',44,69,'bless');
INSERT INTO "DEMONS" VALUES (100,'Nigi Mitama','wind','Temperance',1,'IbesqPT.png',3,12,'electricity');
INSERT INTO "DEMONS" VALUES (101,'Norn','wind','Fortune',3,'i6r1OAr.png',35,62,'electricity');
INSERT INTO "DEMONS" VALUES (102,'Oberon','electricity','Emperor',1,'2tgSBgZ.png',9,15,'ice');
INSERT INTO "DEMONS" VALUES (103,'Odin','electricity','Emperor',3,'VECeHa9.png',47,57,'wind');
INSERT INTO "DEMONS" VALUES (104,'Okuninushi','fire','Temperance',2,'bVdD1Q3.png',29,44,'ice');
INSERT INTO "DEMONS" VALUES (105,'Omoikane','electricity','Hierophant',1,'VnLUY9U.png',6,7,'ice');
INSERT INTO "DEMONS" VALUES (106,'Orobas','Magician','wind',1,'HapAI1B.png',14,28,'ice');
INSERT INTO "DEMONS" VALUES (107,'Orpheus','fire','Fool',0,'QfXYTAc.png',1,10,'electricity');
INSERT INTO "DEMONS" VALUES (108,'Orpheus Telos','almighty','Fool',0,'3bxagie.png',90,100,NULL);
INSERT INTO "DEMONS" VALUES (109,'Orthrus','fire','Hanged Man',1,'lg2a9VP.png',11,28,'ice');
INSERT INTO "DEMONS" VALUES (110,'Ose','physical','Fool',1,'C9CPydq.png',7,22,'electricity');
INSERT INTO "DEMONS" VALUES (111,'Oumitsunu','physical','Chariot',1,'Bnvzmfl.png',14,30,'wind');
INSERT INTO "DEMONS" VALUES (112,'Pale Rider','curse','Death',1,'uiUma6J.png',15,24,'bless');
INSERT INTO "DEMONS" VALUES (113,'Parvati','ice','Priestess',2,'f3mUKXR.png',10,35,'fire');
INSERT INTO "DEMONS" VALUES (114,'Pazuzu','curse','Devil',3,'QfcEHxa.png',37,52,'bless');
INSERT INTO "DEMONS" VALUES (115,'Pixie','electricity','Lovers',1,'dXY0UOA.png',1,2,'fire');
INSERT INTO "DEMONS" VALUES (116,'Power','bless','Justice',1,'L4xjLcD.png',20,25,'curse');
INSERT INTO "DEMONS" VALUES (117,'Principality','bless','Justice',1,'xmDxeRY.png',8,16,'curse');
INSERT INTO "DEMONS" VALUES (118,'Pyro Jack','fire','Magician',1,'zw29e8x.png',4,14,'ice');
INSERT INTO "DEMONS" VALUES (119,'Queen Mab','electricity','Lovers',1,'vubTX4l.png',6,27,'physical');
INSERT INTO "DEMONS" VALUES (120,'Quetzalcoatl','wind','Sun',2,'ygXfXlq.png',21,43,'curse');
INSERT INTO "DEMONS" VALUES (121,'Raja Naga','physical','Emperor',2,'pcWkDCQ.png',16,36,'fire');
INSERT INTO "DEMONS" VALUES (122,'Rakshasa','physical','Strength',1,'KWMrcU0.png',10,16,'bless');
INSERT INTO "DEMONS" VALUES (123,'Rangda','physical','Magician',2,'9vo3lTS.png',21,40,'ice');
INSERT INTO "DEMONS" VALUES (124,'Raphael','physical','Lovers',2,'iELnxPa.png',46,61,'curse');
INSERT INTO "DEMONS" VALUES (125,'Saki Mitama','ice','Lovers',2,'mEcz0zo.png',26,39,'physical');
INSERT INTO "DEMONS" VALUES (126,'Samael','curse','Death',2,'LENjQp9.png',10,35,'bless');
INSERT INTO "DEMONS" VALUES (127,'Sandalphon','bless','Moon',3,'lLJEEYL.png',50,71,'curse');
INSERT INTO "DEMONS" VALUES (128,'Sarasvati','ice','Priestess',1,'BtljaE5.png',12,18,'fire');
INSERT INTO "DEMONS" VALUES (129,'Satan','fire','Judgement',4,'5Mgo5eG.png',70,79,'wind');
INSERT INTO "DEMONS" VALUES (130,'Sati','fire','Magician',1,'6X22aEJ.png',10,20,'ice');
INSERT INTO "DEMONS" VALUES (131,'Saturnus','fire','Star',4,'gQGUyDL.png',62,78,'ice');
INSERT INTO "DEMONS" VALUES (132,'Scathach','physical','Priestess',3,'mTnwKlk.png',42,60,'fire');
INSERT INTO "DEMONS" VALUES (133,'Seiryuu','ice','Temperance',2,'hcYqbff.png',15,36,'fire');
INSERT INTO "DEMONS" VALUES (134,'Seiten Taisei','physical','Tower',3,'An8Liz5.png',34,67,'fire');
INSERT INTO "DEMONS" VALUES (135,'Seth','fire','Moon',3,'5d0t8fk.png',45,66,'bless');
INSERT INTO "DEMONS" VALUES (136,'Shiisaa','ice','Hierophant',1,'yk2P0VD.png',17,26,'fire');
INSERT INTO "DEMONS" VALUES (137,'Shiva','electricity','Tower',4,'WGAUqmg.png',68,82,'ice');
INSERT INTO "DEMONS" VALUES (138,'Siegfried','physical','Strength',3,'P7D1q34.png',43,55,'curse');
INSERT INTO "DEMONS" VALUES (139,'Skadi','ice','Empress',3,'z6EiOxF.png',60,75,'fire');
INSERT INTO "DEMONS" VALUES (140,'Slime','fire','Fool',1,'rMjqK2p.png',6,12,'curse');
INSERT INTO "DEMONS" VALUES (141,'Succubus','fire','Devil',3,'MWcBoNR.png',44,51,'bless');
INSERT INTO "DEMONS" VALUES (142,'Suparna','wind','Sun',3,'IeeJBwG.png',59,70,'physical');
INSERT INTO "DEMONS" VALUES (143,'Surt','fire','Magician',2,'cJYI3NV.png',26,50,'ice');
INSERT INTO "DEMONS" VALUES (144,'Susano-o','physical','Fool',4,'nE4pU4C.png',56,76,'bless');
INSERT INTO "DEMONS" VALUES (145,'Suzaku','fire','Temperance',3,'19E2Uia.png',37,51,'ice');
INSERT INTO "DEMONS" VALUES (146,'Take-Mikazuchi','electricity','Emperor',1,'jIkFKVQ.png',10,24,'ice');
INSERT INTO "DEMONS" VALUES (147,'Take-Minakata','electricity','Hanged Man',1,'EOqhb8x.png',13,21,'bless');
INSERT INTO "DEMONS" VALUES (148,'Taraka','physical','Hermit',2,'oyxEXpO.png',18,32,'ice');
INSERT INTO "DEMONS" VALUES (149,'Thanatos','curse','Death',3,'PM8NR6w.png',50,64,'bless');
INSERT INTO "DEMONS" VALUES (150,'Thor','electricity','Chariot',3,'RuyZgYT.png',45,53,'wind');
INSERT INTO "DEMONS" VALUES (151,'Thoth','electricity','Hierophant',2,'hCjiaJ7.png',26,41,'wind');
INSERT INTO "DEMONS" VALUES (152,'Throne','bless','Justice',3,'m1uJ9EB.png',36,51,'curse');
INSERT INTO "DEMONS" VALUES (153,'Titan','physical','Strength',1,'IqSeX1y.png',15,21,'fire');
INSERT INTO "DEMONS" VALUES (154,'Titania','ice','Lovers',2,'QC6ukAQ.png',25,50,'electricity');
INSERT INTO "DEMONS" VALUES (155,'Trumpeter','bless','Judgement',3,'E0PbRan.png',36,65,'fire');
INSERT INTO "DEMONS" VALUES (156,'Ubelluris','physical','Hanged Man',2,'xpXa90A.png',27,48,'wind');
INSERT INTO "DEMONS" VALUES (157,'Unicorn','electricity','Priestess',1,'H8Mnjd6.png',3,11,'ice');
INSERT INTO "DEMONS" VALUES (158,'Uriel','fire','Tower',3,'0WAp8rj.png',39,54,'curse');
INSERT INTO "DEMONS" VALUES (159,'Valkyrie','physical','Strength',1,'4rxiDHu.png',9,13,'fire');
INSERT INTO "DEMONS" VALUES (160,'Vasuki','bless','Hanged Man',2,'G4XZ1YC.png',23,38,'wind');
INSERT INTO "DEMONS" VALUES (161,'Vetala','curse','Devil',1,'eHfq2Ao.png',9,23,'wind');
INSERT INTO "DEMONS" VALUES (162,'Virtue','bless','Justice',2,'HBxde6P.png',18,32,'curse');
INSERT INTO "DEMONS" VALUES (163,'Vishnu','physical','Sun',4,'MEYMXR5.png',69,78,'curse');
INSERT INTO "DEMONS" VALUES (164,'Yaksini','ice','Empress',2,'IrHiIYX.png',28,50,'fire');
INSERT INTO "DEMONS" VALUES (165,'Yamata no Orochi','ice','Moon',1,'oMDco9M.png',13,26,'fire');
INSERT INTO "DEMONS" VALUES (166,'Yatagarasu','wind','Sun',1,'KgLkIZI.png',16,30,'ice');
INSERT INTO "DEMONS" VALUES (167,'Yomotsu-Shikome','curse','Hermit',1,'Mpbc7la.png',4,9,'fire');
INSERT INTO "DEMONS" VALUES (168,'Yurlungur','ice','Temperance',3,'YNzbwux.png',41,64,'electricity');
INSERT INTO "DEMONS" VALUES (169,'Zouchouten','physical','Chariot',1,'YfnmFjF.png',8,14,'wind');
INSERT INTO "DEMONS" VALUES (170,'Izanagi','electricity','Fool',0,'N5zDaH9.png',1,10,'wind');
INSERT INTO "DEMONS" VALUES (171,'Izanagi-no-Okami','almighty','Fool',0,'9O0JZLp.png',90,100,NULL);
INSERT INTO "DEMONS" VALUES (172,'Maia','ice','Moon',0,'E4QTeCA.png',1,10,'fire');
INSERT INTO "DEMONS" VALUES (173,'Artemis','almighty','Moon',0,'qmKU2sk.png',90,100,NULL);
INSERT INTO "DEMONS" VALUES (174,'Oni','physical','Strength',1,'pTXVDQv.png',20,30,NULL);
INSERT INTO "DEMONS" VALUES (175,'Mada','fire','Magician',4,'mrAqLdq.png',57,78,'ice');
INSERT INTO "DEMONS" VALUES (176,'Pabilsag','physical','Emperor',3,'AUQvUii.png',37,51,'ice');
INSERT INTO "DEMONS" VALUES (177,'Kin-Ki','physical','Chariot',3,'K4XLT7K.png',40,54,NULL);
INSERT INTO "DEMONS" VALUES (178,'Ongyo-Ki','physical','Hermit',4,'IZqhwcE.png',68,82,'bless');
INSERT INTO "DEMONS" VALUES (179,'Kaguya Hime','bless','Moon',3,'tEDmSCd.png',52,74,'fire');
INSERT INTO "DEMONS" VALUES (180,'Gorgon','ice','Empress',2,'txMtnbY.png',17,34,'bless');
INSERT INTO "DEMONS" VALUES (181,'Mahakala','physical','Death',4,'WxniN8L.png',65,78,NULL);
INSERT INTO "DEMONS" VALUES (182,'Futsunushi','physical','Chariot',4,'9CKfiuD.png',61,80,'curse');
INSERT INTO "DEMONS" VALUES (183,'Zaou-Gongen','fire','Chariot',4,'GAl33l9.png',63,90,'electricity');
INSERT INTO "DEMONS" VALUES (184,'Isis','ice','Empress',4,'q1TMhGJ.png',59,79,'electricity');
INSERT INTO "DEMONS" VALUES (185,'Baphomet','curse','Devil',2,'7LeIEs4.png',30,47,'bless');
INSERT INTO "DEMONS" VALUES (186,'Ardha','physical','Judgement',4,'q2HAWPw.png',72,90,NULL);
INSERT INTO "DEMONS" VALUES (187,'Cerberus','fire','Hierophant',3,'U1TqWox.png',36,52,'ice');
INSERT INTO "DEMONS" VALUES (188,'Belial','curse','Devil',3,'z8z1X04.png',37,68,NULL);
INSERT INTO "DEMONS" VALUES (189,'Fuu-ki','wind','Star',2,'CmVhPV1.png',24,43,'fire');
INSERT INTO "DEMONS" VALUES (190,'Gdon','fire','Sun',2,'4UG0ykb.png',16,31,'ice');
INSERT INTO "DEMONS" VALUES (191,'Hachiman','electricity','Hierophant',3,'IgSOdqO.png',35,70,'curse');
INSERT INTO "DEMONS" VALUES (192,'Anzu','wind','Hierophant',1,'Ka0G13Y.png',5,15,'fire');
INSERT INTO "DEMONS" VALUES (193,'White Rider','curse','Death',3,'5l3aJ5N.png',36,58,'ice');
INSERT INTO "DEMONS" VALUES (194,'Taown','wind','Hanged Man',3,'iunSmlG.png',38,56,'fire');
INSERT INTO "DEMONS" VALUES (195,'Tzitzimitl','electricity','Priestess',3,'DwHMb8g.png',45,70,'wind');
INSERT INTO "DEMONS" VALUES (196,'Sui-Ki','ice','Moon',3,'xdkC1Yw.png',33,57,'fire');
INSERT INTO "DEMONS" VALUES (197,'Tam Lin','physical','Sun',3,'u6lRM4z.png',38,53,NULL);
INSERT INTO "DEMONS" VALUES (198,'Kushinada Hime','bless','Lovers',2,'I4bwLNP.png',23,44,'curse');
INSERT INTO "DEMONS" VALUES (199,'Shiki-Ouji','fire','Fool',3,'LwHXqmv.png',39,56,'wind');
INSERT INTO "DEMONS" VALUES (200,'Ame no Uzume','wind','Priestess',1,'Zzgen3O.png',13,18,'electricity');
INSERT INTO "DEMONS" VALUES (201,'Undine','ice','Lovers',2,'MC2Xp57.png',21,33,'fire');
INSERT INTO "DEMONS" VALUES (202,'Hitokoto-Nushi','wind','Hermit',2,'eD3cMem.png',15,41,'fire');
INSERT INTO "DEMONS" VALUES (203,'Belphegor','electricity','Devil',3,'is7WQpZ.png',33,61,'bless');
INSERT INTO "DEMONS" VALUES (204,'Ippon-Datara','curse','Hermit',1,'DPNiJ17.png',7,17,'bless');
INSERT INTO "DEMONS" VALUES (205,'Sraosha','bless','Justice',3,'9q7fZyK.png',40,74,'curse');
INSERT INTO "DEMONS" VALUES (206,'Ishtar','bless','Lovers',3,'MCEnTuK.png',44,71,'wind');
INSERT INTO "DEMONS" VALUES (207,'Yomotsu-Ikusa','curse','Hanged Man',1,'jnyA3il.png',5,22,'fire');
INSERT INTO "DEMONS" VALUES (208,'Sylph','wind','Temperance',1,'IIYYizG.png',2,11,'electricity');
INSERT INTO "DEMONS" VALUES (209,'Matador','physical','Death',1,'9n44EPe.png',9,24,'fire');
INSERT INTO "DEMONS" VALUES (210,'Tao Tie','curse','Tower',2,'jNhDfFc.png',11,35,'physical');
INSERT INTO "DEMONS" VALUES (211,'Yatsufusa','fire','Hanged Man',2,'qrlGtBa.png',22,49,'physical');
INSERT INTO "DEMONS" VALUES (212,'Mokoi','ice','Death',1,'MgHvYDf.png',4,14,'fire');
INSERT INTO "DEMONS" VALUES (213,'Ukobach','fire','Devil',1,'09WtysO.png',1,3,'ice');
INSERT INTO "DEMONS" VALUES (214,'Jinn','fire','Magician',3,'pmgQPoV.png',34,62,'electricity');
INSERT INTO "DEMONS" VALUES (215,'Cu Sith','wind','Sun',1,'msnL4fQ.png',4,10,'fire');
INSERT INTO "DEMONS" VALUES (216,'Alraune','bless','Moon',2,'8yQPNv5.png',20,41,'wind');
INSERT INTO "DEMONS" VALUES (217,'Triglav','physical','Chariot',2,'6guAcJT.png',22,43,'electricity');
INSERT INTO "DEMONS" VALUES (218,'Andras','bless','Moon',1,'AiE10IU.png',11,20,'wind');
INSERT INTO "DEMONS" VALUES (219,'Senri','fire','Empress',1,'0pJf1tW.png',6,9,'electricity');
INSERT INTO "DEMONS" VALUES (220,'Neko Shogun','electricity','Star',2,'hP3OQTG.png',16,32,'wind');
INSERT INTO "DEMONS" VALUES (221,'Nozuchi','electricity','Moon',1,'19opY0U.png',8,27,'ice');
INSERT INTO "DEMONS" VALUES (222,'Dis','fire','Magician',2,'iIsSOSz.png',19,39,'ice');
INSERT INTO "DEMONS" VALUES (223,'Xiezhai','electricity','Temperance',1,'XmKEeEJ.png',8,16,'wind');
INSERT INTO "DEMONS" VALUES (224,'Setanta','electricity','Emperor',2,'e5iG9MX.png',13,34,'fire');
INSERT INTO "DEMONS" VALUES (225,'Makami','fire','Hanged Man',1,'SOVQnqp.png',15,27,'ice');
INSERT INTO "DEMONS" VALUES (226,'Phoenix','wind','Sun',1,'w0ziOAh.png',14,20,'ice');
INSERT INTO "DEMONS" VALUES (227,'Sandman','wind','Strength',1,'kEn7LIB.png',4,5,'electricity');
COMMIT;
